/* kmamba_distributed.cu — NCCL multi-GPU implementation (optional) */

#include "kmamba_distributed.h"
#include <cuda_runtime.h>
#include <stdio.h>

#ifdef KMAMBA_USE_NCCL
#include <nccl.h>

/* ============================================================================
 * NCCL Implementation
 * ============================================================================ */

typedef struct {
    KMambaDistributedConfig config;
    ncclComm_t nccl_comm;
    cudaStream_t stream;
    float *nccl_scratch;
    size_t scratch_size;
} KMambaNCCLContext;

KMambaDistributedContext* kmamba_distributed_init_nccl(int world_size, int rank) {
    #ifdef KMAMBA_USE_NCCL
    if (world_size <= 1) {
        /* Single GPU, NCCL not needed */
        return NULL;
    }
    
    KMambaNCCLContext *ctx = (KMambaNCCLContext*)calloc(1, sizeof(*ctx));
    if (!ctx) return NULL;
    
    ctx->config.world_size = world_size;
    ctx->config.rank = rank;
    ctx->config.local_rank = rank;  /* Assume single node for now */
    ctx->config.use_nccl = 1;
    ctx->config.use_p2p = 0;
    
    /* Set device for this rank */
    cudaSetDevice(rank);
    
    /* Create CUDA stream */
    cudaStreamCreate(&ctx->stream);
    
    /* Initialize NCCL communicator
     * For single node, use unique ID generated by rank 0 */
    ncclUniqueId id;
    if (rank == 0) {
        ncclGetUniqueId(&id);
    }
    /* Broadcast unique ID to all ranks (simplified - would need MPI or similar) */
    /* For now, assume single process per GPU model */
    
    ncclResult_t res = ncclCommInitRank(&ctx->nccl_comm, world_size, id, rank);
    if (res != ncclSuccess) {
        fprintf(stderr, "NCCL init failed: %s\n", ncclGetErrorString(res));
        free(ctx);
        return NULL;
    }
    
    /* Allocate scratch buffer for allreduce */
    ctx->scratch_size = 1024 * 1024 * sizeof(float);  /* 1M floats default */
    cudaMalloc(&ctx->nccl_scratch, ctx->scratch_size);
    
    return (KMambaDistributedContext*)ctx;
    #else
    (void)world_size; (void)rank;
    return NULL;  /* NCCL not compiled in */
    #endif
}

void kmamba_distributed_fini_nccl(KMambaDistributedContext *ctx) {
    #ifdef KMAMBA_USE_NCCL
    if (!ctx) return;
    
    KMambaNCCLContext *nctx = (KMambaNCCLContext*)ctx;
    
    cudaFree(nctx->nccl_scratch);
    ncclCommDestroy(nctx->nccl_comm);
    cudaStreamDestroy(nctx->stream);
    free(nctx);
    #else
    (void)ctx;
    #endif
}

int kmamba_allreduce_gradients_nccl(KMambaDistributedContext *ctx,
                                       float *d_gradients,
                                       size_t n_elements) {
    #ifdef KMAMBA_USE_NCCL
    if (!ctx || !d_gradients) return -1;
    
    KMambaNCCLContext *nctx = (KMambaNCCLContext*)ctx;
    if (!nctx->config.use_nccl) return -1;
    
    /* All-reduce: sum gradients from all GPUs */
    ncclResult_t res = ncclAllReduce(d_gradients, d_gradients, n_elements,
                                     ncclFloat, ncclSum,
                                     nctx->nccl_comm, nctx->stream);
    
    if (res != ncclSuccess) {
        fprintf(stderr, "NCCL allreduce failed: %s\n", ncclGetErrorString(res));
        return -1;
    }
    
    cudaStreamSynchronize(nctx->stream);
    return 0;
    #else
    (void)ctx; (void)d_gradients; (void)n_elements;
    return -1;
    #endif
}

int kmamba_broadcast_params_nccl(KMambaDistributedContext *ctx,
                                  float *d_params,
                                  size_t n_elements) {
    #ifdef KMAMBA_USE_NCCL
    if (!ctx || !d_params) return -1;
    
    KMambaNCCLContext *nctx = (KMambaNCCLContext*)ctx;
    if (!nctx->config.use_nccl) return -1;
    
    /* Broadcast from rank 0 to all */
    ncclResult_t res = ncclBroadcast(d_params, d_params, n_elements,
                                     ncclFloat, 0,  /* root = rank 0 */
                                     nctx->nccl_comm, nctx->stream);
    
    if (res != ncclSuccess) {
        fprintf(stderr, "NCCL broadcast failed: %s\n", ncclGetErrorString(res));
        return -1;
    }
    
    cudaStreamSynchronize(nctx->stream);
    return 0;
    #else
    (void)ctx; (void)d_params; (void)n_elements;
    return -1;
    #endif
}

#endif /* KMAMBA_USE_NCCL */
